
server:
  port: 7000
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MYSQL;
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
logging:
  level:
    '[org.springframework.web]': DEBUG
    '[com.example.side]': DEBUG